import turtle
wn=turtle.Screen()
wn.bgcolor("yellow")
wn.title("mintesnot, argaw")
alex=turtle.Turtle()
alex.color("blue")
alex.pensize(10)
alex.left(120)
alex.forward(150)
alex.left(120)
alex.forward(150)
alex.left(152)
alex.forward(190)
alex.left(148)
alex.forward(175)
alex.left(148)
alex.forward(190)
wn.mainloop()